spring:
    datasource:
      url: jdbc:mysql://108.61.246.175:3306/stdb
      username: usrsta
      password: usrsta
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties.hibernate.format_sql: true
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

spring.profiles: logging-info
logging:
  file: logs/application.log
  level:
    root: INFO

    org:
      springframework.web: INFO
 #  org.hibernate.SQL: INFO


spring.profiles: logging-debug
logging:
  file: logs/application.log
  level:
    org:
      springframework:
        security: DEBUG
    org:
      springframework.web: DEBUG
     # org.hibernate.SQL: DEBUG

spring.profiles: logging-daily
logging:
  config:
    classpath: logback-spring.xml